name: running

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: pulling
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ma2tg:latest

      - name: running
        run: |
          docker run \
          -e BOT_TOKEN=${{secrets.BOT_TOKEN}} \
          -e BOT_CHAT_ID=${{secrets.BOT_CHAT_ID}} \
          -e MA_USERNAME=${{secrets.MA_USERNAME}} \
          -e MA_PASSWORD=${{secrets.MA_PASSWORD}} \
          ${{ secrets.DOCKER_HUB_USERNAME }}/ma2tg:latest
